import type { DecisionSimulation } from "./types";

export const decisionSimulationMock: DecisionSimulation = {
  id: "sim-memory-feed-home",
  generatedAt: "2026-07-07T18:05:00+05:30",
  inputContext: {
    decisionId: "decision-memory-feed-home",
    decisionTitle: "Make Memory Feed the default home surface",
    personalKnowledgeSignals: ["User values continuity over tool switching.", "User prefers small, ranked surfaces instead of exhaustive dashboards."],
    decisionGraphConnections: ["Supports goal-return-user-clarity", "Influenced by memory-context-visible", "Blocked by risk-feed-overload"],
    goals: ["Improve return-user clarity", "Increase daily retention"],
    missions: ["Synzept V2 Intelligence Foundation"],
    projects: ["Memory Feed", "Workspace OS"],
    memories: ["Context should always be visible", "Limit feed to 5-7 cards"],
    riskPreference: "Moderate: prefer controlled rollout with explicit explanations.",
    pastOutcomeSignals: ["Mock-first contracts produced 87% prediction accuracy.", "Overbuilding before integration is a recurring blind spot."],
  },
  scenarios: [
    {
      id: "scenario-feed-default",
      title: "Make Memory Feed the default home",
      summary: "Open Synzept directly into a ranked feed of memories, decisions, loops, progress, and suggested next actions.",
      potentialBenefits: ["Highest alignment with return-user clarity.", "Creates a daily ritual around remembered context.", "Makes decisions and commitments visible before users ask."],
      potentialRisks: ["Could feel noisy if ranking explanations are weak.", "May hide project-level controls if users expect a dashboard."],
      assumptions: ["Feed remains limited to 5-7 cards.", "Users trust why-card explanations.", "Daily refresh produces enough novelty without churn."],
      confidence: 0.82,
      bestCaseOutcome: "Users understand what matters within one minute and return daily.",
      worstCaseOutcome: "Users perceive the feed as opaque and look for the old dashboard.",
      keyUncertainties: ["Ranking quality", "Card fatigue", "First-week beta feedback"],
      comparison: { effort: 62, risk: 58, cost: 35, time: 48, goalAlignment: 92, expectedImpact: 90 },
    },
    {
      id: "scenario-workspace-home",
      title: "Use Workspace Home as the default",
      summary: "Open into a broader operating surface with mission, focus, agents, approvals, knowledge, opportunities, loops, and daily brief.",
      potentialBenefits: ["Gives users stable context and visible controls.", "Balances proactive intelligence with workspace navigation.", "Better foundation for agents and approvals."],
      potentialRisks: ["May dilute Memory Feed's sharp daily recall value.", "More sections could slow mobile scanning."],
      assumptions: ["Home remains minimal and scannable.", "Command bar and search reduce navigation overhead.", "Agents need visible approval queues."],
      confidence: 0.78,
      bestCaseOutcome: "Synzept feels like an OS while keeping context visible.",
      worstCaseOutcome: "The home surface becomes a dashboard again and loses proactive recall.",
      keyUncertainties: ["Mobile density", "Agent trust readiness", "Navigation complexity"],
      comparison: { effort: 76, risk: 52, cost: 44, time: 66, goalAlignment: 84, expectedImpact: 88 },
    },
    {
      id: "scenario-chat-default",
      title: "Open directly into Ask Synzept",
      summary: "Make chat the first screen and let users ask for memory, decisions, tasks, and next actions as needed.",
      potentialBenefits: ["Familiar AI pattern.", "Flexible for ambiguous user intent.", "Lower upfront UI complexity."],
      potentialRisks: ["Forces users to ask before seeing forgotten context.", "Weakens proactive decision and commitment recall.", "Can repeat the generic AI-app pattern."],
      assumptions: ["Users know what to ask.", "Chat retrieval can reconstruct context quickly.", "Proactive recall is less important than flexibility."],
      confidence: 0.64,
      bestCaseOutcome: "Users rely on chat as a flexible command center.",
      worstCaseOutcome: "Users must re-explain work and Synzept feels like a generic assistant.",
      keyUncertainties: ["Prompt friction", "Retrieval quality", "User habit formation"],
      comparison: { effort: 38, risk: 72, cost: 30, time: 34, goalAlignment: 61, expectedImpact: 63 },
    },
  ],
  finalChoice: {
    scenarioId: "scenario-workspace-home",
    chosenAt: "2026-07-07T18:20:00+05:30",
    rationale: "Workspace Home preserves mission context while Memory Feed remains a core module inside the daily surface.",
    status: "recorded_mock",
  },
  learning: {
    id: "learn-sim-memory-feed-home",
    scenarioId: "scenario-workspace-home",
    predictedResult: "Synzept feels like an OS while keeping context visible.",
    actualResult: "Early mock review showed better navigation clarity, but Memory Feed needed stronger prominence.",
    accuracy: 79,
    lessonsLearned: ["A broader home works if daily recall remains first-class.", "Agent approvals need a compact summary, not a large panel."],
  },
};
