import type { WorkspaceOSData } from "./types";

export const workspaceOSMock: WorkspaceOSData = {
  generatedAt: "2026-07-07T16:45:00+05:30",
  navigation: [
    { id: "home", label: "Home", href: "/dashboard", icon: "home" },
    { id: "missions", label: "Missions", href: "/mission", icon: "target" },
    { id: "knowledge", label: "Knowledge", href: "/memory", icon: "book-open" },
    { id: "projects", label: "Projects", href: "/projects", icon: "folder-kanban" },
    { id: "agents", label: "Agents", href: "/agents", icon: "bot" },
    { id: "daily-os", label: "Daily OS", href: "/daily-brief", icon: "calendar-days" },
    { id: "search", label: "Search", href: "/search", icon: "search" },
    { id: "settings", label: "Settings", href: "/settings", icon: "settings" },
  ],
  home: {
    currentMission: {
      id: "mission-v3-workspace-os",
      title: "Transform Synzept into a Workspace OS",
      status: "active",
      progress: 64,
      currentMilestone: "Unify home, search, command bar, and agent workspace around user work.",
      nextStep: "Ship the mock Workspace OS shell and route all V3 surfaces through it.",
    },
    todaysFocus: [
      {
        title: "Stabilize the Workspace Home",
        reason: "It becomes the first place users understand mission, focus, approvals, agents, and knowledge.",
        estimatedTime: "35 min",
        linkedItems: ["mission-v3-workspace-os", "agent-product-architect"],
      },
      {
        title: "Define global search filters",
        reason: "Search connects conversations, decisions, tasks, files, and people.",
        estimatedTime: "25 min",
        linkedItems: ["search-unified-index"],
      },
    ],
    activeAgents: [
      {
        id: "agent-product-architect",
        name: "Product Architect",
        goal: "Keep V3 centered on work outcomes instead of isolated tools.",
        status: "planning next milestone",
        recentActivity: ["Mapped Workspace Home sections", "Prioritized persistent navigation"],
        plannedNextSteps: ["Review IA", "Draft command set", "Identify approval boundaries"],
        approvalsAwaitingUser: ["Approve replacing Dashboard with Workspace Home"],
      },
      {
        id: "agent-research",
        name: "Research Scout",
        goal: "Surface relevant knowledge, decisions, and opportunities for the current mission.",
        status: "monitoring knowledge updates",
        recentActivity: ["Found two recent decisions", "Linked beta feedback to onboarding opportunity"],
        plannedNextSteps: ["Summarize recent knowledge", "Flag stale open loops"],
        approvalsAwaitingUser: [],
      },
    ],
    pendingApprovals: [
      {
        id: "approval-home-replacement",
        title: "Replace Dashboard with Workspace Home",
        requestedBy: "Product Architect",
        riskLevel: "medium",
        preview: "The first authenticated screen becomes a unified operating surface.",
        status: "pending",
      },
      {
        id: "approval-beta-draft",
        title: "Draft private beta invite",
        requestedBy: "Research Scout",
        riskLevel: "low",
        preview: "Creates a draft only; Synzept will not contact anyone.",
        status: "pending",
      },
    ],
    recentKnowledge: [
      {
        id: "knowledge-principle-context",
        title: "Context should always be visible",
        kind: "principle",
        summary: "Users should not reconstruct work state when switching between goals, projects, and agents.",
        source: "Product notes",
        updatedAt: "2026-07-07T15:50:00+05:30",
      },
      {
        id: "knowledge-decision-command-bar",
        title: "Universal Command Bar is part of the OS shell",
        kind: "decision",
        summary: "Commands must be accessible from anywhere, not buried inside a page.",
        source: "Architecture session",
        updatedAt: "2026-07-07T15:30:00+05:30",
      },
      {
        id: "knowledge-beta-feedback",
        title: "Beta reviewers need a focused ask",
        kind: "memory",
        summary: "Ask for feedback on first-run clarity instead of asking for broad product review.",
        source: "Relationship graph",
        updatedAt: "2026-07-06T19:20:00+05:30",
      },
    ],
    opportunities: [
      {
        id: "opp-retention-ritual",
        title: "Make Workspace Home the daily return ritual",
        expectedImpact: 91,
        confidence: 78,
        suggestedAction: "Show mission, focus, agents, approvals, and brief in one scannable view.",
      },
      {
        id: "opp-agent-approval-trust",
        title: "Use approvals to build trust in active agents",
        expectedImpact: 84,
        confidence: 73,
        suggestedAction: "Keep every meaningful agent action behind explicit approval.",
      },
    ],
    openLoops: [
      { id: "loop-search", title: "Decide search ranking weights", owner: "Workspace OS", dueLabel: "Today", urgency: "High" },
      { id: "loop-agent-ux", title: "Define agent activity summaries", owner: "Agent Workspace", dueLabel: "Tomorrow", urgency: "Medium" },
      { id: "loop-knowledge", title: "Group decisions and memories into Knowledge", owner: "Knowledge", dueLabel: "This week", urgency: "Medium" },
    ],
    dailyBrief: {
      headline: "The product is ready to become a unified workspace layer.",
      whatChanged: [
        "Memory Feed became a first-screen pattern.",
        "The Intelligence Loop now provides a platform contract.",
        "V3 needs a persistent shell so every surface feels connected.",
      ],
      reminders: ["Keep navigation simple.", "Do not connect production data yet.", "Agents must ask approval before meaningful action."],
      recommendedNextAction: "Implement Workspace Home using realistic mock data and route Dashboard to it.",
    },
  },
  searchIndex: [
    { id: "search-conversation-v3", type: "conversation", title: "Workspace OS planning conversation", snippet: "Transform Synzept from an AI app into an AI Workspace Operating System.", href: "/chat", source: "Conversation", updatedAt: "2026-07-07T16:35:00+05:30", tags: ["workspace", "v3"] },
    { id: "search-memory-context", type: "memory", title: "Context always visible", snippet: "Every workspace view should preserve mission, focus, and next action context.", href: "/memory", source: "Memory", updatedAt: "2026-07-07T15:50:00+05:30", tags: ["principle"] },
    { id: "search-project-workspace", type: "project", title: "Workspace OS Shell", snippet: "Persistent navigation, command bar, global search, and home overview.", href: "/projects", source: "Project", updatedAt: "2026-07-07T16:10:00+05:30", tags: ["frontend", "shell"] },
    { id: "search-task-command", type: "task", title: "Add universal command bar", snippet: "Support create mission, find decision, focus session, ask Synzept, and capture thought.", href: "/dashboard", source: "Task", updatedAt: "2026-07-07T16:18:00+05:30", tags: ["command"] },
    { id: "search-file-ia", type: "file", title: "Workspace OS IA draft", snippet: "Home, Missions, Knowledge, Projects, Agents, Daily OS, Search, Settings.", href: "/dashboard", source: "File", updatedAt: "2026-07-07T15:45:00+05:30", tags: ["ia"] },
    { id: "search-decision-dashboard", type: "decision", title: "Dashboard becomes Workspace Home", snippet: "The first authenticated screen should be organized around work context, not tools.", href: "/dashboard", source: "Decision", updatedAt: "2026-07-07T16:00:00+05:30", tags: ["home"] },
    { id: "search-person-aarav", type: "people", title: "Aarav", snippet: "Potential beta reviewer for first-run clarity and onboarding feedback.", href: "/memory", source: "Relationship", updatedAt: "2026-07-06T19:20:00+05:30", tags: ["beta", "feedback"] },
    { id: "search-mission-v3", type: "mission", title: "Transform Synzept into Workspace OS", snippet: "Unify goals, projects, knowledge, conversations, and AI agents.", href: "/mission", source: "Mission", updatedAt: "2026-07-07T16:45:00+05:30", tags: ["mission", "v3"] },
  ],
  commands: [
    { id: "cmd-create-mission", title: "Create a mission", description: "Start a new outcome-centered workspace mission.", category: "Create", shortcut: "M", requiresInput: true },
    { id: "cmd-find-decision", title: "Find a decision", description: "Search decisions across conversations, notes, and memory.", category: "Search", shortcut: "D", requiresInput: true },
    { id: "cmd-focus-session", title: "Start a focus session", description: "Begin a focused work block tied to today's focus.", category: "Action", shortcut: "F", requiresInput: false },
    { id: "cmd-ask-synzept", title: "Ask Synzept", description: "Ask a workspace-aware question.", category: "AI", shortcut: "A", requiresInput: true },
    { id: "cmd-capture-thought", title: "Capture a thought", description: "Save a quick note into Knowledge.", category: "Capture", shortcut: "C", requiresInput: true },
  ],
  agents: [],
  designPrinciples: ["Minimal interface", "Fast performance", "Context always visible", "Consistent design system", "Mobile-first responsiveness"],
};

workspaceOSMock.agents = workspaceOSMock.home.activeAgents;
