MOCK_RAW_EVENTS = [
    {
        "id": "conv-2026-07-07-memory-feed",
        "source": "conversation",
        "eventType": "decision",
        "title": "Memory Feed should become the first screen",
        "description": "The product should proactively surface what to remember, what changed, and what needs attention.",
        "occurredAt": "2026-07-07T08:45:00+05:30",
        "actor": "user",
        "entities": ["Memory Feed", "Synzept V2"],
        "signals": ["home_screen", "proactive_recall", "product_direction"],
        "importance": 94,
        "urgency": 78,
        "metadata": {"feature": "memory_feed"},
    },
    {
        "id": "mission-2026-v2",
        "source": "mission",
        "eventType": "progress",
        "title": "Synzept V2 intelligence surfaces are converging",
        "description": "Action Center, Opportunity Engine, Trust Engine, Life Graph, and Memory Feed now have mock foundations.",
        "occurredAt": "2026-07-07T09:10:00+05:30",
        "actor": "system",
        "entities": ["Synzept V2", "Action Center", "Opportunity Engine", "Trust Engine", "Life Graph"],
        "signals": ["momentum", "integration_needed"],
        "importance": 88,
        "urgency": 66,
        "metadata": {"progress": 72},
    },
    {
        "id": "project-beta-invites",
        "source": "project",
        "eventType": "open_loop",
        "title": "Beta invite flow is still open",
        "description": "Three early reviewers are waiting for a private beta link and focused onboarding ask.",
        "occurredAt": "2026-07-07T08:35:00+05:30",
        "actor": "user",
        "entities": ["Private Beta", "Aarav"],
        "signals": ["external_commitment", "deadline_risk"],
        "importance": 91,
        "urgency": 94,
        "metadata": {"waitingPeople": 3},
    },
    {
        "id": "task-onboarding-feedback",
        "source": "task",
        "eventType": "deadline",
        "title": "Onboarding feedback request due tomorrow",
        "description": "The review request should be scoped to three questions instead of the full product.",
        "occurredAt": "2026-07-06T19:20:00+05:30",
        "actor": "system",
        "entities": ["Aarav", "Onboarding"],
        "signals": ["relationship", "deadline"],
        "importance": 76,
        "urgency": 73,
        "metadata": {"dueInHours": 27},
    },
    {
        "id": "note-product-principle",
        "source": "note",
        "eventType": "memory",
        "title": "Users should not reconstruct context",
        "description": "The recurring product principle is to reduce mental reloading for returning users.",
        "occurredAt": "2026-07-04T09:00:00+05:30",
        "actor": "user",
        "entities": ["Product Principle", "Continuity"],
        "signals": ["north_star", "retention"],
        "importance": 84,
        "urgency": 44,
        "metadata": {"principle": "continuity"},
    },
    {
        "id": "memory-working-pattern",
        "source": "memory",
        "eventType": "pattern",
        "title": "Best progress happens when the next step is small",
        "description": "Recent accepted actions were scoped to 15 to 30 minute implementation increments.",
        "occurredAt": "2026-07-05T21:10:00+05:30",
        "actor": "system",
        "entities": ["Working Pattern"],
        "signals": ["execution_style", "small_steps"],
        "importance": 72,
        "urgency": 38,
        "metadata": {"averageActionMinutes": 22},
    },
    {
        "id": "decision-no-production-data",
        "source": "decision",
        "eventType": "constraint",
        "title": "Use realistic mock data before production integrations",
        "description": "V2 foundations should be testable without connecting to production data.",
        "occurredAt": "2026-07-07T08:48:00+05:30",
        "actor": "user",
        "entities": ["Architecture", "Mock Data"],
        "signals": ["safety_boundary", "implementation_constraint"],
        "importance": 86,
        "urgency": 80,
        "metadata": {"productionData": False},
    },
]

MOCK_LEARNING_OUTCOMES = [
    {
        "id": "learn-001",
        "targetId": "rec-focus-beta-invite",
        "targetType": "recommendation",
        "outcome": "accepted",
        "adjustment": "Increase weight for external commitments with near-term deadlines.",
        "recordedAt": "2026-07-07T09:20:00+05:30",
        "note": "User asked Synzept to draft the invite.",
    },
    {
        "id": "learn-002",
        "targetId": "rec-add-new-surface",
        "targetType": "recommendation",
        "outcome": "rejected",
        "adjustment": "Reduce priority for adding new surfaces before integration work is complete.",
        "recordedAt": "2026-07-06T18:05:00+05:30",
        "note": "User chose consolidation over expansion.",
    },
]
