MOCK_DECISION_GRAPH = {
    "generatedAt": "2026-07-07T17:40:00+05:30",
    "supportedRelationships": [
        "influenced_by",
        "supports",
        "blocks",
        "resulted_in",
        "contradicts",
        "related_to",
        "reviewed_by",
        "learned_from",
    ],
    "nodes": [
        {
            "id": "decision-memory-feed-home",
            "type": "decision",
            "title": "Make Memory Feed the default home surface",
            "description": "Use a ranked first screen to show what changed, what matters, and what needs attention.",
            "timestamp": "2026-07-07T08:45:00+05:30",
            "confidence": 0.84,
            "status": "Accepted",
            "importance": "High",
            "metadata": {"reviewState": "Pending"},
        },
        {
            "id": "decision-mock-first",
            "type": "decision",
            "title": "Build V2 intelligence systems with realistic mock data first",
            "description": "Prove service contracts, ranking, and UX before production data integration.",
            "timestamp": "2026-07-06T18:10:00+05:30",
            "confidence": 0.89,
            "status": "Accepted",
            "importance": "High",
            "metadata": {"reviewState": "Completed"},
        },
        {
            "id": "decision-approval-layer",
            "type": "decision",
            "title": "Require explicit approval before meaningful agent actions",
            "description": "Agents may prepare drafts and plans but must ask before changing state or contacting people.",
            "timestamp": "2026-07-07T10:20:00+05:30",
            "confidence": 0.82,
            "status": "Accepted",
            "importance": "Critical",
            "metadata": {"reviewState": "Outcome Unknown"},
        },
        {
            "id": "mission-v2-intelligence",
            "type": "mission",
            "title": "Synzept V2 Intelligence Foundation",
            "description": "Create the central intelligence layer for memory, decisions, opportunities, agents, and trust.",
            "timestamp": "2026-07-07T09:00:00+05:30",
            "confidence": 0.91,
            "status": "Active",
            "importance": "Critical",
            "metadata": {"progress": 68},
        },
        {
            "id": "goal-return-user-clarity",
            "type": "goal",
            "title": "Improve return-user clarity",
            "description": "Users should understand their work state without reconstructing context.",
            "timestamp": "2026-07-07T08:00:00+05:30",
            "confidence": 0.86,
            "status": "Active",
            "importance": "High",
            "metadata": {},
        },
        {
            "id": "project-memory-feed",
            "type": "project",
            "title": "Memory Feed",
            "description": "Rank and present the most relevant information from history and current context.",
            "timestamp": "2026-07-07T08:30:00+05:30",
            "confidence": 0.88,
            "status": "Active",
            "importance": "High",
            "metadata": {},
        },
        {
            "id": "project-agent-workspace",
            "type": "project",
            "title": "Agent Workspace",
            "description": "Display agent goals, activity, next steps, and approval requests.",
            "timestamp": "2026-07-07T10:00:00+05:30",
            "confidence": 0.77,
            "status": "Active",
            "importance": "High",
            "metadata": {},
        },
        {
            "id": "person-beta-reviewers",
            "type": "people",
            "title": "Beta reviewers",
            "description": "Early users who can validate first-run clarity and trust boundaries.",
            "timestamp": "2026-07-06T19:20:00+05:30",
            "confidence": 0.72,
            "status": "Active",
            "importance": "Medium",
            "metadata": {},
        },
        {
            "id": "memory-context-visible",
            "type": "memory",
            "title": "Context should always be visible",
            "description": "Returning users should not reconstruct state when switching work modes.",
            "timestamp": "2026-07-04T09:00:00+05:30",
            "confidence": 0.81,
            "status": "Validated",
            "importance": "High",
            "metadata": {},
        },
        {
            "id": "conversation-memory-feed-requirements",
            "type": "conversation",
            "title": "Memory Feed requirements conversation",
            "description": "Defined the feed objective, card types, ranking, actions, and UI requirements.",
            "timestamp": "2026-07-07T08:35:00+05:30",
            "confidence": 0.9,
            "status": "Captured",
            "importance": "High",
            "metadata": {},
        },
        {
            "id": "evidence-five-seven-cards",
            "type": "evidence",
            "title": "Limit feed to 5-7 cards",
            "description": "Avoid overload by keeping the daily feed small and ranked.",
            "timestamp": "2026-07-07T08:42:00+05:30",
            "confidence": 0.93,
            "status": "Accepted",
            "importance": "Medium",
            "metadata": {},
        },
        {
            "id": "alternative-static-dashboard",
            "type": "alternative",
            "title": "Keep static dashboard",
            "description": "Continue using a dashboard organized around sections rather than proactive recall.",
            "timestamp": "2026-07-07T08:40:00+05:30",
            "confidence": 0.66,
            "status": "Rejected",
            "importance": "Medium",
            "metadata": {},
        },
        {
            "id": "risk-feed-overload",
            "type": "risk",
            "title": "Feed overload",
            "description": "Too many cards or opaque ranking could reduce clarity.",
            "timestamp": "2026-07-07T08:43:00+05:30",
            "confidence": 0.79,
            "status": "Open",
            "importance": "High",
            "metadata": {},
        },
        {
            "id": "outcome-mock-first",
            "type": "outcome",
            "title": "Mock-first accelerated V2 systems",
            "description": "Multiple engines shipped with service, API, UI, docs, and tests before production wiring.",
            "timestamp": "2026-07-07T18:00:00+05:30",
            "confidence": 0.83,
            "status": "Completed",
            "importance": "High",
            "metadata": {"predictionAccuracy": 87},
        },
        {
            "id": "lesson-contract-tests",
            "type": "lesson",
            "title": "Contract tests matter more than visual-only prototypes",
            "description": "Future intelligence systems should pair mock UI with service/API contract tests.",
            "timestamp": "2026-07-07T18:10:00+05:30",
            "confidence": 0.84,
            "status": "Learned",
            "importance": "High",
            "metadata": {},
        },
    ],
    "edges": [
        {
            "id": "edge-memory-feed-supports-goal",
            "source": "decision-memory-feed-home",
            "target": "goal-return-user-clarity",
            "relationship": "supports",
            "label": "Supports return-user clarity",
            "strength": 91,
            "evidence": ["conversation-memory-feed-requirements", "memory-context-visible"],
        },
        {
            "id": "edge-memory-feed-related-project",
            "source": "decision-memory-feed-home",
            "target": "project-memory-feed",
            "relationship": "related_to",
            "label": "Implemented through Memory Feed",
            "strength": 94,
            "evidence": ["conversation-memory-feed-requirements"],
        },
        {
            "id": "edge-memory-feed-influenced-context",
            "source": "decision-memory-feed-home",
            "target": "memory-context-visible",
            "relationship": "influenced_by",
            "label": "Influenced by context visibility principle",
            "strength": 88,
            "evidence": ["memory-context-visible"],
        },
        {
            "id": "edge-memory-feed-influenced-conversation",
            "source": "decision-memory-feed-home",
            "target": "conversation-memory-feed-requirements",
            "relationship": "influenced_by",
            "label": "Requirements drove the choice",
            "strength": 90,
            "evidence": ["conversation-memory-feed-requirements"],
        },
        {
            "id": "edge-memory-feed-influenced-evidence",
            "source": "decision-memory-feed-home",
            "target": "evidence-five-seven-cards",
            "relationship": "influenced_by",
            "label": "Ranking must avoid overload",
            "strength": 86,
            "evidence": ["evidence-five-seven-cards"],
        },
        {
            "id": "edge-static-dashboard-contradicts-feed",
            "source": "alternative-static-dashboard",
            "target": "decision-memory-feed-home",
            "relationship": "contradicts",
            "label": "Rejected alternative",
            "strength": 72,
            "evidence": ["conversation-memory-feed-requirements"],
        },
        {
            "id": "edge-risk-blocks-feed",
            "source": "risk-feed-overload",
            "target": "decision-memory-feed-home",
            "relationship": "blocks",
            "label": "Could weaken the decision outcome",
            "strength": 74,
            "evidence": ["evidence-five-seven-cards"],
        },
        {
            "id": "edge-mock-first-resulted-outcome",
            "source": "decision-mock-first",
            "target": "outcome-mock-first",
            "relationship": "resulted_in",
            "label": "Produced mock-first delivery outcome",
            "strength": 93,
            "evidence": ["outcome-mock-first"],
        },
        {
            "id": "edge-mock-first-learned-contract",
            "source": "outcome-mock-first",
            "target": "lesson-contract-tests",
            "relationship": "learned_from",
            "label": "Generated contract-testing lesson",
            "strength": 89,
            "evidence": ["lesson-contract-tests"],
        },
        {
            "id": "edge-approval-supports-agent",
            "source": "decision-approval-layer",
            "target": "project-agent-workspace",
            "relationship": "supports",
            "label": "Supports trustworthy agent UX",
            "strength": 87,
            "evidence": ["person-beta-reviewers"],
        },
        {
            "id": "edge-approval-influenced-reviewers",
            "source": "decision-approval-layer",
            "target": "person-beta-reviewers",
            "relationship": "influenced_by",
            "label": "Beta trust concerns influenced the boundary",
            "strength": 70,
            "evidence": ["person-beta-reviewers"],
        },
        {
            "id": "edge-decisions-related-mission",
            "source": "decision-mock-first",
            "target": "mission-v2-intelligence",
            "relationship": "related_to",
            "label": "Part of V2 intelligence foundation",
            "strength": 92,
            "evidence": ["mission-v2-intelligence"],
        },
        {
            "id": "edge-feed-related-mission",
            "source": "decision-memory-feed-home",
            "target": "mission-v2-intelligence",
            "relationship": "related_to",
            "label": "Part of V2 intelligence foundation",
            "strength": 90,
            "evidence": ["mission-v2-intelligence"],
        },
    ],
    "chains": [
        {
            "id": "chain-memory-feed-cause-effect",
            "title": "Memory Feed cause-and-effect chain",
            "nodeIds": [
                "memory-context-visible",
                "conversation-memory-feed-requirements",
                "decision-memory-feed-home",
                "project-memory-feed",
                "goal-return-user-clarity",
            ],
            "edgeIds": [
                "edge-memory-feed-influenced-context",
                "edge-memory-feed-influenced-conversation",
                "edge-memory-feed-related-project",
                "edge-memory-feed-supports-goal",
            ],
            "summary": "A product principle and requirements conversation led to a home-screen decision that supports return-user clarity.",
        },
        {
            "id": "chain-mock-first-learning",
            "title": "Mock-first learning chain",
            "nodeIds": ["decision-mock-first", "outcome-mock-first", "lesson-contract-tests"],
            "edgeIds": ["edge-mock-first-resulted-outcome", "edge-mock-first-learned-contract"],
            "summary": "The mock-first decision produced a measurable outcome and a reusable lesson for future systems.",
        },
    ],
    "insights": [
        {
            "id": "insight-pattern-mock-first",
            "type": "frequently_repeated_pattern",
            "title": "Mock-first architecture is becoming a high-performing pattern",
            "summary": "The mock-first decision connects to a successful outcome and a lesson about contract tests.",
            "supportingConnectionIds": ["edge-mock-first-resulted-outcome", "edge-mock-first-learned-contract"],
            "confidence": 0.86,
            "impact": 88,
        },
        {
            "id": "insight-high-impact-feed",
            "type": "high_impact_decision",
            "title": "Memory Feed is a key turning point for product shape",
            "summary": "It connects mission, goal, project, evidence, risk, and rejected alternative nodes.",
            "supportingConnectionIds": [
                "edge-memory-feed-supports-goal",
                "edge-memory-feed-related-project",
                "edge-static-dashboard-contradicts-feed",
                "edge-risk-blocks-feed",
            ],
            "confidence": 0.84,
            "impact": 91,
        },
        {
            "id": "insight-failure-path-overload",
            "type": "common_failure_path",
            "title": "Overload is the most visible failure path",
            "summary": "The feed decision is blocked by overload risk and depends on limiting the card count.",
            "supportingConnectionIds": ["edge-risk-blocks-feed", "edge-memory-feed-influenced-evidence"],
            "confidence": 0.78,
            "impact": 80,
        },
        {
            "id": "insight-success-cluster-clarity",
            "type": "success_cluster",
            "title": "Clarity cluster links memory, feed, and mission",
            "summary": "Context visibility, Memory Feed, and return-user clarity reinforce the same product direction.",
            "supportingConnectionIds": [
                "edge-memory-feed-influenced-context",
                "edge-memory-feed-supports-goal",
                "edge-feed-related-mission",
            ],
            "confidence": 0.81,
            "impact": 86,
        },
    ],
}
