MOCK_LIFE_GRAPH = {
    "entities": [
        {"id": "mission-1", "type": "Mission", "title": "Launch Synzept V2", "summary": "Turn Synzept into a calm continuity operating system.", "tags": ["product", "vision"], "metadata": {"owner": "founder"}},
        {"id": "goal-1", "type": "Goal", "title": "Improve daily activation", "summary": "Increase the share of users who experience value in the first week.", "tags": ["growth"], "metadata": {"priority": "high"}},
        {"id": "project-1", "type": "Project", "title": "Life Graph Engine", "summary": "Build the graph layer that connects all Synzept context.", "tags": ["engineering"], "metadata": {"status": "in-progress"}},
        {"id": "task-1", "type": "Task", "title": "Implement explorer page", "summary": "Ship a mock graph explorer for product teams.", "tags": ["ui"], "metadata": {"projectId": "project-1"}},
        {"id": "note-1", "type": "Note", "title": "Onboarding friction", "summary": "Users stall when setup feels long.", "tags": ["insight"], "metadata": {"projectId": "project-1"}},
        {"id": "memory-1", "type": "Memory", "title": "Daily brief drives activation", "summary": "Users who reach the brief are more likely to return.", "tags": ["behavior"], "metadata": {"conversationId": "conversation-1"}},
        {"id": "conversation-1", "type": "Conversation", "title": "Founder review", "summary": "Discussion around onboarding and retention improvements.", "tags": ["research"], "metadata": {"personId": "person-1"}},
        {"id": "person-1", "type": "Person", "title": "Maya Chen", "summary": "Product lead and early adopter.", "tags": ["stakeholder"], "metadata": {"companyId": "company-1"}},
        {"id": "company-1", "type": "Company", "title": "Synzept", "summary": "The operating system for continuity and memory.", "tags": ["company"], "metadata": {"industry": "software"}},
        {"id": "event-1", "type": "Event", "title": "Product review", "summary": "Review session for life graph concepts.", "tags": ["meeting"], "metadata": {"date": "2026-07-01"}},
        {"id": "decision-1", "type": "Decision", "title": "Prioritize onboarding", "summary": "Make onboarding shorter and more visible to users.", "tags": ["strategy"], "metadata": {"missionId": "mission-1"}},
        {"id": "document-1", "type": "Document", "title": "Roadmap v2", "summary": "Contains the graph architecture plan.", "tags": ["planning"], "metadata": {"projectId": "project-1"}},
        {"id": "file-1", "type": "File", "title": "graph-spec.txt", "summary": "Design notes for the graph explorer experience.", "tags": ["asset"], "metadata": {"projectId": "project-1"}},
        {"id": "meeting-1", "type": "Meeting", "title": "Founder sync", "summary": "Weekly sync about product improvements.", "tags": ["meeting"], "metadata": {"personId": "person-1"}},
        {"id": "habit-1", "type": "Habit", "title": "Daily review", "summary": "Review key priorities before new work begins.", "tags": ["routine"], "metadata": {"goalId": "goal-1"}},
        {"id": "insight-1", "type": "Insight", "title": "Daily Brief drives activation", "summary": "Evidence shows early discovery improves engagement.", "tags": ["analysis"], "metadata": {"source": "mock"}},
    ],
    "relationships": [
        {"id": "rel-1", "source": "task-1", "target": "project-1", "type": "belongs_to", "direction": "outgoing", "strength": 0.95, "evidence": "Task created inside project"},
        {"id": "rel-2", "source": "task-1", "target": "decision-1", "type": "depends_on", "direction": "outgoing", "strength": 0.74, "evidence": "Task depends on the chosen onboarding strategy"},
        {"id": "rel-3", "source": "project-1", "target": "mission-1", "type": "created_from", "direction": "outgoing", "strength": 0.91, "evidence": "Project supports the parent mission"},
        {"id": "rel-4", "source": "note-1", "target": "project-1", "type": "references", "direction": "outgoing", "strength": 0.8, "evidence": "Note references the project context"},
        {"id": "rel-5", "source": "memory-1", "target": "conversation-1", "type": "mentioned_in", "direction": "outgoing", "strength": 0.88, "evidence": "Memory originated from the conversation"},
        {"id": "rel-6", "source": "conversation-1", "target": "person-1", "type": "discussed_with", "direction": "outgoing", "strength": 0.82, "evidence": "Conversation centered on this person"},
        {"id": "rel-7", "source": "decision-1", "target": "mission-1", "type": "belongs_to", "direction": "outgoing", "strength": 0.9, "evidence": "Decision affects the mission"},
        {"id": "rel-8", "source": "document-1", "target": "project-1", "type": "references", "direction": "outgoing", "strength": 0.79, "evidence": "Document references the project"},
        {"id": "rel-9", "source": "file-1", "target": "project-1", "type": "related_to", "direction": "outgoing", "strength": 0.7, "evidence": "File supports the project artifact"},
        {"id": "rel-10", "source": "meeting-1", "target": "person-1", "type": "discussed_with", "direction": "outgoing", "strength": 0.78, "evidence": "Meeting focused on this stakeholder"},
        {"id": "rel-11", "source": "habit-1", "target": "goal-1", "type": "belongs_to", "direction": "outgoing", "strength": 0.71, "evidence": "Habit supports the goal"},
        {"id": "rel-12", "source": "insight-1", "target": "memory-1", "type": "related_to", "direction": "outgoing", "strength": 0.86, "evidence": "Insight reinforces the memory"},
    ],
}
