MOCK_SKILL_CATALOG = [
  {
    "id": "skill-market-1",
    "name": "Launch Planner",
    "description": "Turn a product vision into a crisp launch plan.",
    "author": "Synzept Labs",
    "version": "1.2.0",
    "category": "Startup",
    "rating": 4.8,
    "reviews": 124,
    "featured": True,
    "trending": True,
    "new": False,
    "installed": True,
    "enabled": True,
    "permissions": ["Memory access", "Tasks", "Projects"],
    "integrations": ["Tasks", "Projects"],
    "screenshots": ["launch-planner.png"],
    "documentation": "https://example.com/docs/launch-planner",
    "changelog": ["Improved milestone recommendations", "Better conflict detection"]
  },
  {
    "id": "skill-market-2",
    "name": "Weekly Review",
    "description": "Review the week and identify the biggest gain.",
    "author": "Synzept Labs",
    "version": "1.0.0",
    "category": "Productivity",
    "rating": 4.6,
    "reviews": 84,
    "featured": False,
    "trending": True,
    "new": True,
    "installed": False,
    "enabled": False,
    "permissions": ["Calendar", "Tasks", "Memory access"],
    "integrations": ["Calendar", "Tasks"],
    "screenshots": ["weekly-review.png"],
    "documentation": "https://example.com/docs/weekly-review",
    "changelog": ["Initial release"]
  },
  {
    "id": "skill-market-3",
    "name": "Knowledge Graph Builder",
    "description": "Connect notes, memories, and projects into a graph.",
    "author": "Independent Builder",
    "version": "2.1.0",
    "category": "Knowledge",
    "rating": 4.9,
    "reviews": 203,
    "featured": True,
    "trending": False,
    "new": False,
    "installed": True,
    "enabled": False,
    "permissions": ["Memory access", "Files", "Projects"],
    "integrations": ["Files", "Projects"],
    "screenshots": ["knowledge-graph.png"],
    "documentation": "https://example.com/docs/knowledge-graph",
    "changelog": ["Added duplicate detection", "Improved entity linking"]
  },
  {
    "id": "skill-market-4",
    "name": "Habit Review",
    "description": "Review habits and suggest the next improvement.",
    "author": "Synzept Labs",
    "version": "0.9.0",
    "category": "Personal",
    "rating": 4.4,
    "reviews": 55,
    "featured": False,
    "trending": False,
    "new": True,
    "installed": False,
    "enabled": False,
    "permissions": ["Calendar", "Memory access"],
    "integrations": ["Calendar"],
    "screenshots": ["habit-review.png"],
    "documentation": "https://example.com/docs/habit-review",
    "changelog": ["Initial beta release"]
  }
]
