import type { SynzeptProtocolData } from "./types";

export const synzeptProtocolMock: SynzeptProtocolData = {
  version: "2026-07-07.v1",
  generatedAt: "2026-07-07T19:15:00+05:30",
  principles: [
    "User-owned data",
    "Explicit permission for every data category",
    "Fine-grained access controls",
    "Revocable permissions",
    "Audit logs for all data sharing",
    "Extensible schema",
  ],
  resourceTypes: ["profile", "goals", "missions", "projects", "decisions", "knowledge", "memories", "relationships", "preferences"],
  resources: [
    {
      id: "profile-self",
      type: "profile",
      version: "v1",
      owner: "user",
      title: "User profile",
      summary: "Minimal profile fields safe for approved integrations.",
      updatedAt: "2026-07-07T19:00:00+05:30",
      schemaUrl: "https://protocol.synzept.local/schemas/v1/profile.json",
      data: { displayName: "Piyush", timezone: "Asia/Kolkata", locale: "en-IN" },
    },
    {
      id: "goal-return-user-clarity",
      type: "goals",
      version: "v1",
      owner: "user",
      title: "Improve return-user clarity",
      summary: "Users should understand their work state without reconstructing context.",
      updatedAt: "2026-07-07T18:40:00+05:30",
      schemaUrl: "https://protocol.synzept.local/schemas/v1/goal.json",
      data: { status: "active", confidence: 0.86, linkedMissions: ["mission-v2-intelligence"] },
    },
    {
      id: "mission-v2-intelligence",
      type: "missions",
      version: "v1",
      owner: "user",
      title: "Synzept V2 Intelligence Foundation",
      summary: "Create the central intelligence layer for memory, decisions, opportunities, agents, and trust.",
      updatedAt: "2026-07-07T18:50:00+05:30",
      schemaUrl: "https://protocol.synzept.local/schemas/v1/mission.json",
      data: { status: "active", progress: 68, linkedGoals: ["goal-return-user-clarity"] },
    },
    {
      id: "project-memory-feed",
      type: "projects",
      version: "v1",
      owner: "user",
      title: "Memory Feed",
      summary: "Rank and present the most relevant information from user history and current context.",
      updatedAt: "2026-07-07T18:30:00+05:30",
      schemaUrl: "https://protocol.synzept.local/schemas/v1/project.json",
      data: { status: "active", priority: "high", linkedDecisions: ["decision-memory-feed-home"] },
    },
    {
      id: "decision-memory-feed-home",
      type: "decisions",
      version: "v1",
      owner: "user",
      title: "Make Memory Feed the default home surface",
      summary: "Open Synzept into a ranked first screen for memories, decisions, loops, and next actions.",
      updatedAt: "2026-07-07T08:45:00+05:30",
      schemaUrl: "https://protocol.synzept.local/schemas/v1/decision.json",
      data: { status: "accepted", importance: "high", confidence: 0.84 },
    },
    {
      id: "knowledge-context-visible",
      type: "knowledge",
      version: "v1",
      owner: "user",
      title: "Context should always be visible",
      summary: "Returning users should not reconstruct work state when switching between goals, projects, and agents.",
      updatedAt: "2026-07-07T15:50:00+05:30",
      schemaUrl: "https://protocol.synzept.local/schemas/v1/knowledge.json",
      data: { kind: "principle", confidence: 0.81, tags: ["continuity"] },
    },
    {
      id: "memory-limit-feed",
      type: "memories",
      version: "v1",
      owner: "user",
      title: "Limit feed to 5-7 cards",
      summary: "Avoid overload by keeping the daily feed small and ranked.",
      updatedAt: "2026-07-07T08:42:00+05:30",
      schemaUrl: "https://protocol.synzept.local/schemas/v1/memory.json",
      data: { confidence: 0.93, sensitivity: "private" },
    },
    {
      id: "relationship-beta-reviewers",
      type: "relationships",
      version: "v1",
      owner: "user",
      title: "Beta reviewers",
      summary: "Early users who can validate first-run clarity and trust boundaries.",
      updatedAt: "2026-07-06T19:20:00+05:30",
      schemaUrl: "https://protocol.synzept.local/schemas/v1/relationship.json",
      data: { relationshipType: "reviewer_group", privacy: "requires_explicit_permission" },
    },
    {
      id: "preference-privacy",
      type: "preferences",
      version: "v1",
      owner: "user",
      title: "Privacy preference",
      summary: "Default to explicit approval and local-only private context.",
      updatedAt: "2026-07-07T18:55:00+05:30",
      schemaUrl: "https://protocol.synzept.local/schemas/v1/preference.json",
      data: { defaultSharing: "deny", anonymousContribution: true },
    },
  ],
  permissionGrants: [
    {
      id: "grant-calendar-focus",
      appId: "app-focus-calendar",
      appName: "Focus Calendar",
      resourceType: "goals",
      scopes: ["read:summary", "read:status"],
      status: "active",
      grantedAt: "2026-07-07T18:00:00+05:30",
      expiresAt: "2026-08-07T18:00:00+05:30",
      purpose: "Show goal-aligned focus blocks.",
    },
    {
      id: "grant-research-notes",
      appId: "app-research-notes",
      appName: "Research Notes",
      resourceType: "knowledge",
      scopes: ["read:summary", "write:note_link"],
      status: "active",
      grantedAt: "2026-07-07T18:15:00+05:30",
      expiresAt: null,
      purpose: "Link external research notes to Synzept knowledge.",
    },
    {
      id: "grant-old-crm",
      appId: "app-old-crm",
      appName: "Old CRM",
      resourceType: "relationships",
      scopes: ["read:summary"],
      status: "revoked",
      grantedAt: "2026-06-20T12:00:00+05:30",
      expiresAt: "2026-07-01T12:00:00+05:30",
      purpose: "Past relationship lookup.",
    },
  ],
  subscriptions: [
    {
      id: "sub-focus-goals",
      appId: "app-focus-calendar",
      resourceType: "goals",
      eventTypes: ["updated", "completed"],
      callbackUrl: "https://focus-calendar.example.dev/synzept/webhook",
      status: "active",
      createdAt: "2026-07-07T18:05:00+05:30",
    },
  ],
  auditLogs: [
    {
      id: "audit-protocol-001",
      appId: "app-focus-calendar",
      appName: "Focus Calendar",
      action: "read",
      resourceType: "goals",
      scopes: ["read:summary", "read:status"],
      timestamp: "2026-07-07T18:20:00+05:30",
      result: "allowed",
      userVisibleSummary: "Focus Calendar read goal summaries and status.",
    },
    {
      id: "audit-protocol-002",
      appId: "app-old-crm",
      appName: "Old CRM",
      action: "read",
      resourceType: "relationships",
      scopes: ["read:summary"],
      timestamp: "2026-07-07T18:25:00+05:30",
      result: "denied_revoked",
      userVisibleSummary: "Old CRM was denied because its relationship permission was revoked.",
    },
  ],
  apps: [
    {
      id: "app-focus-calendar",
      name: "Focus Calendar",
      description: "Creates calendar blocks aligned with active Synzept goals.",
      redirectUris: ["https://focus-calendar.example.dev/oauth/callback"],
      allowedScopes: ["goals:read:summary", "goals:read:status", "missions:read:summary"],
      sampleUseCase: "Create focus blocks without reading private memories or conversations.",
    },
    {
      id: "app-research-notes",
      name: "Research Notes",
      description: "Links external research notes to Synzept knowledge.",
      redirectUris: ["https://research-notes.example.dev/oauth/callback"],
      allowedScopes: ["knowledge:read:summary", "knowledge:write:note_link"],
      sampleUseCase: "Attach source links to knowledge nodes with user approval.",
    },
  ],
  sdks: [
    {
      language: "TypeScript",
      packageName: "@synzept/protocol",
      installCommand: "npm install @synzept/protocol",
      modules: ["auth", "resources", "permissions", "subscriptions", "audit"],
      example: "const goals = await client.resources.list({ type: 'goals', scope: 'read:summary' });",
    },
    {
      language: "Python",
      packageName: "synzept-protocol",
      installCommand: "pip install synzept-protocol",
      modules: ["auth", "resources", "permissions", "subscriptions", "audit"],
      example: "goals = client.resources.list(type='goals', scope='read:summary')",
    },
  ],
  authFlow: {
    flow: "OAuth 2.1 authorization code with PKCE",
    steps: [
      "App registers redirect URI and requested resource scopes.",
      "User reviews every requested data category and scope.",
      "Synzept issues short-lived access token and scoped refresh token after explicit approval.",
      "Every resource read/write checks active grants and writes an audit event.",
      "User can revoke any grant; future calls fail immediately.",
    ],
    tokenRules: [
      "Access tokens are scoped by resource type and action.",
      "Refresh tokens are revocable per app.",
      "Tokens never grant raw memories unless the user explicitly approves that category.",
    ],
  },
};
