import { rankMemoryFeedCards } from "./ranking";
import type { MemoryFeedResponse, MemoryFeedCard } from "./types";

export const memoryFeedCards: MemoryFeedCard[] = [
  {
    id: "mf-001",
    type: "open_loop",
    title: "Close the beta tester invite loop",
    summary: "Three people are waiting for the private beta link and onboarding note.",
    detail: "You mentioned wanting the first beta cohort to feel personally invited before widening access.",
    source: "Chat, launch checklist, relationship notes",
    timestamp: "2026-07-07T08:35:00+05:30",
    dueAt: "2026-07-07T18:00:00+05:30",
    project: "Synzept V2",
    tags: ["launch", "commitment", "beta"],
    factors: [
      { label: "Relevance", value: 96 },
      { label: "Urgency", value: 94 },
      { label: "Importance", value: 91 },
      { label: "Recency", value: 88 },
      { label: "Feedback", value: 76 },
    ],
    suggestedAction: "Draft and send the private beta invite.",
    followUpPrompt: "Draft the beta invite from my notes.",
  },
  {
    id: "mf-002",
    type: "recent_decision",
    title: "Decision: Memory Feed becomes the default home",
    summary: "The first screen should answer what changed, what matters, and what needs attention.",
    detail: "This shifts Synzept from a static dashboard toward proactive memory recall.",
    source: "Product planning notes",
    timestamp: "2026-07-07T07:50:00+05:30",
    project: "Memory Feed",
    tags: ["product", "decision", "home"],
    factors: [
      { label: "Relevance", value: 98 },
      { label: "Urgency", value: 72 },
      { label: "Importance", value: 95 },
      { label: "Recency", value: 93 },
      { label: "Feedback", value: 82 },
    ],
    pinned: true,
    suggestedAction: "Review the feed cards and ranking behavior.",
    followUpPrompt: "Explain the home feed architecture.",
  },
  {
    id: "mf-003",
    type: "relationship_reminder",
    title: "Follow up with Aarav about onboarding feedback",
    summary: "He offered to review the first-run experience after the prototype stabilizes.",
    detail: "The last note says to send a focused ask, not the whole product.",
    source: "Relationship graph",
    timestamp: "2026-07-06T19:20:00+05:30",
    dueAt: "2026-07-08T12:00:00+05:30",
    relatedPerson: "Aarav",
    tags: ["relationship", "feedback"],
    factors: [
      { label: "Relevance", value: 82 },
      { label: "Urgency", value: 69 },
      { label: "Importance", value: 74 },
      { label: "Recency", value: 81 },
      { label: "Feedback", value: 64 },
    ],
    suggestedAction: "Send a 3-question review request.",
    followUpPrompt: "What should I ask Aarav?",
  },
  {
    id: "mf-004",
    type: "mission_progress",
    title: "Mission progress: V2 intelligence layer is converging",
    summary: "Recent work added opportunities, action center, trust, and life graph foundations.",
    detail: "The next leverage point is connecting these surfaces into one daily recall loop.",
    source: "Project activity",
    timestamp: "2026-07-06T17:15:00+05:30",
    project: "Synzept V2",
    tags: ["progress", "architecture"],
    factors: [
      { label: "Relevance", value: 90 },
      { label: "Urgency", value: 58 },
      { label: "Importance", value: 84 },
      { label: "Recency", value: 78 },
      { label: "Feedback", value: 70 },
    ],
    suggestedAction: "Document the feed contract before connecting real retrieval.",
    followUpPrompt: "Summarize my V2 progress this week.",
  },
  {
    id: "mf-005",
    type: "opportunity",
    title: "Opportunity: turn Memory Feed into a retention ritual",
    summary: "Daily refresh plus clear actions can make Synzept feel useful immediately after opening.",
    detail: "This aligns with the product principle: return users should not reconstruct context.",
    source: "AI synthesis of product notes",
    timestamp: "2026-07-07T06:40:00+05:30",
    tags: ["opportunity", "retention"],
    factors: [
      { label: "Relevance", value: 88 },
      { label: "Urgency", value: 64 },
      { label: "Importance", value: 87 },
      { label: "Recency", value: 91 },
      { label: "Feedback", value: 67 },
    ],
    suggestedAction: "Add a daily feed review event to the roadmap.",
    followUpPrompt: "How can this improve retention?",
  },
  {
    id: "mf-006",
    type: "achievement",
    title: "Achievement: shipped core mock intelligence surfaces",
    summary: "Action Center, Opportunity Engine, Trust Engine, and Life Graph now have mock service paths.",
    detail: "This creates a good testbed for the feed before production integrations.",
    source: "Repository activity",
    timestamp: "2026-07-05T21:10:00+05:30",
    tags: ["achievement", "engineering"],
    factors: [
      { label: "Relevance", value: 78 },
      { label: "Urgency", value: 32 },
      { label: "Importance", value: 70 },
      { label: "Recency", value: 65 },
      { label: "Feedback", value: 73 },
    ],
    suggestedAction: "Archive completed implementation notes.",
    followUpPrompt: "What did I complete recently?",
  },
  {
    id: "mf-007",
    type: "ai_insight",
    title: "Insight: your highest leverage work is integration",
    summary: "Many V2 modules exist; the next risk is fragmentation across screens.",
    detail: "A ranked feed can become the integration surface before deeper automation ships.",
    source: "AI insight",
    timestamp: "2026-07-07T08:10:00+05:30",
    tags: ["insight", "focus"],
    factors: [
      { label: "Relevance", value: 91 },
      { label: "Urgency", value: 73 },
      { label: "Importance", value: 88 },
      { label: "Recency", value: 90 },
      { label: "Feedback", value: 79 },
    ],
    suggestedAction: "Use Memory Feed as the connective tissue for V2.",
    followUpPrompt: "Where is V2 fragmented right now?",
  },
  {
    id: "mf-008",
    type: "weekly_reflection",
    title: "Weekly reflection: fewer surfaces, stronger recall",
    summary: "You repeatedly come back to the same theme: Synzept should reduce mental reloading.",
    detail: "This is a good north star for deciding what appears in the feed.",
    source: "Weekly reflection",
    timestamp: "2026-07-04T09:00:00+05:30",
    tags: ["reflection", "principles"],
    factors: [
      { label: "Relevance", value: 80 },
      { label: "Urgency", value: 28 },
      { label: "Importance", value: 77 },
      { label: "Recency", value: 54 },
      { label: "Feedback", value: 61 },
    ],
    suggestedAction: "Pin this principle to product planning.",
    followUpPrompt: "What principle keeps recurring?",
  },
];

export const memoryFeedMock: MemoryFeedResponse = {
  generatedAt: "2026-07-07T08:45:00+05:30",
  nextRefreshAt: "2026-07-08T08:00:00+05:30",
  refreshLabel: "Daily refresh ready tomorrow at 8:00 AM",
  cards: rankMemoryFeedCards(memoryFeedCards, 7),
};
