from contextlib import asynccontextmanager
import asyncio
import logging
import secrets
from contextlib import suppress

from fastapi import Depends, FastAPI
from fastapi.exceptions import HTTPException, RequestValidationError
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse
from redis import asyncio as redis_async
from starlette.datastructures import MutableHeaders

from sqlalchemy.exc import SQLAlchemyError

from app.api import (
    billing,
    chat,
    connected_apps,
    continue_engine,
    context_engine_phase6,
    continuity_assistant_phase7,
    daily_brief_phase8,
    decision_graph,
    decision_intelligence,
    decision_simulator,
    evolution_engine,
    home,
    intelligence_dataset,
    intelligence_loop,
    life_graph,
    memory_feed,
    opportunity,
    action_center,
    pkm,
    privacy_intelligence,
    reasoning_engine,
    skills,
    skill_marketplace,
    synzept_protocol,
    time_machine,
    trust_engine,
    workspace_os,
    agent_runtime,
    coach,
    onboarding_wow,
    knows_you,
    learning_engine_phase4,
    learning_evaluation,
    notifications,
    open_loops_engine,
    product_analytics,
    project_intelligence_phase2,
    relationship_graph_phase5,
    timeline_phase3,
    daily_engine,
)
from app.api.v2 import executions, execute
from app.api.middleware import BodySizeLimitMiddleware, RateLimitMiddleware, SecurityHeadersMiddleware
from app.api.v1.router import api_router
from app.api.v2.router import api_router as api_v2_router
from app.core.config import build_auth_health_report, get_settings, validate_connected_apps_runtime_settings, validate_google_auth_runtime_settings
from app.core.dependencies import get_current_user
from app.core.exceptions import (
    AppError,
    app_exception_handler,
    database_connection_exception_handler,
    database_exception_handler,
    http_exception_handler,
    unhandled_exception_handler,
    validation_exception_handler as request_validation_exception_handler,
)
from app.core.logging import setup_logging
from app.infrastructure.database import check_database, database_diagnostics, retrieval_diagnostics
from app.infrastructure.monitoring import monitor
from app.services.ai.provider_registry import ProviderRegistry
from app.infrastructure.tracing import RequestTracingMiddleware
from app.database.session import SessionLocal, initialize_local_database
from app.services.notification_service import NotificationService
from app.services.connected_apps.google_calendar_service import GoogleCalendarService
from app.services.connected_apps.microsoft_365_service import Microsoft365Service
from app.services.connected_apps.github_service import GitHubService
from app.services.connected_apps.slack_service import SlackService
from app.services.connected_apps.notion_service import NotionService
from app.agent.initialization import initialize_tool_registry

settings = get_settings()
logger = logging.getLogger(__name__)

CORS_ORIGINS = settings.cors_origin_list
CORS_METHODS = ["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"]
CORS_HEADERS = ["Accept", "Authorization", "Content-Type", "X-Requested-With"]


class OuterCORSMiddleware(CORSMiddleware):
    """Keep CORS headers on responses generated by FastAPI's outer error handler."""

    def __getattr__(self, name):
        return getattr(self.app, name)

    async def __call__(self, scope, receive, send):
        if scope["type"] != "http":
            await super().__call__(scope, receive, send)
            return

        async def send_with_cors(message):
            if message["type"] == "http.response.start":
                origin = next((value.decode("latin-1") for key, value in scope.get("headers", []) if key == b"origin"), None)
                if origin in self.allow_origins and not any(key.lower() == b"access-control-allow-origin" for key, _value in message.get("headers", [])):
                    headers = MutableHeaders(scope=message)
                    headers["Access-Control-Allow-Origin"] = origin
                    headers["Access-Control-Allow-Credentials"] = "true"
                    headers.add_vary_header("Origin")
            await send(message)

        await super().__call__(scope, receive, send_with_cors)


@asynccontextmanager
async def lifespan(_app: FastAPI):
    setup_logging()
    validate_google_auth_runtime_settings(settings)
    if settings.environment == "production":
        validate_connected_apps_runtime_settings(settings)
    build_auth_health_report(settings)
    from app.core.dependencies import get_current_user
    await initialize_local_database()
    initialize_tool_registry()
    notification_task = asyncio.create_task(_notification_scheduler())
    connected_app_task = asyncio.create_task(_connected_app_scheduler())
    try:
        yield
    finally:
        notification_task.cancel()
        connected_app_task.cancel()
        with suppress(asyncio.CancelledError):
            await notification_task
        with suppress(asyncio.CancelledError):
            await connected_app_task


async def _notification_scheduler() -> None:
    while True:
        lease = await _acquire_scheduler_lease("notifications", 30 * 60 + 60)
        if lease:
            try:
                async with SessionLocal() as session:
                    await NotificationService(session).generate_for_all_users()
                    await session.commit()
            except Exception:
                logger.exception("Notification scheduler cycle failed")
            finally:
                await _release_scheduler_lease(lease)
        await asyncio.sleep(30 * 60)


async def _connected_app_scheduler() -> None:
    while True:
        lease = await _acquire_scheduler_lease("connected-apps", 15 * 60 + 60)
        if lease:
            try:
                async with SessionLocal() as session:
                    await GoogleCalendarService(session).sync_due_accounts()
                    await Microsoft365Service(session).sync_due_accounts()
                    await GitHubService(session).sync_if_due()
                    await SlackService(session).sync_if_due()
                    await NotionService(session).sync_if_due()
                    await session.commit()
            except Exception:
                logger.exception("Connected-app scheduler cycle failed")
            finally:
                await _release_scheduler_lease(lease)
        await asyncio.sleep(15 * 60)


async def _acquire_scheduler_lease(name: str, ttl_seconds: int) -> tuple[object, str] | None:
    if settings.environment != "production":
        return (None, name)
    client = redis_async.from_url(settings.redis_url, decode_responses=True, socket_connect_timeout=1, socket_timeout=1)
    token = secrets.token_urlsafe(24)
    try:
        acquired = await client.set(f"synzept:scheduler:{name}", token, ex=ttl_seconds, nx=True)
        if not acquired:
            await client.aclose()
            return None
        return (client, f"synzept:scheduler:{name}:{token}")
    except Exception:
        await client.aclose()
        logger.exception("Could not acquire %s scheduler lease", name)
        return None


async def _release_scheduler_lease(lease: tuple[object, str]) -> None:
    client, lease_key = lease
    if client is None:
        return
    key, token = lease_key.rsplit(":", 1)
    try:
        await client.eval("if redis.call('get', KEYS[1]) == ARGV[1] then return redis.call('del', KEYS[1]) else return 0 end", 1, key, token)
    except Exception:
        logger.exception("Could not release scheduler lease")
    finally:
        await client.aclose()


app = FastAPI(
    title="Synzept API",
    description="Synzept backend - continuity workspace foundation",
    version="1.0.0",
    lifespan=lifespan,
)

app.add_middleware(RequestTracingMiddleware)
app.add_middleware(RateLimitMiddleware)
app.add_middleware(BodySizeLimitMiddleware)
app.add_middleware(SecurityHeadersMiddleware)


@app.exception_handler(RequestValidationError)
async def validation_exception_handler(_request, exc: RequestValidationError):
    return await request_validation_exception_handler(_request, exc)


app.add_exception_handler(AppError, app_exception_handler)
app.add_exception_handler(HTTPException, http_exception_handler)
app.add_exception_handler(SQLAlchemyError, database_exception_handler)
app.add_exception_handler(OSError, database_connection_exception_handler)
app.add_exception_handler(Exception, unhandled_exception_handler)

app.include_router(api_router)
app.include_router(api_v2_router)
app.include_router(chat.router)
app.include_router(connected_apps.router)
app.include_router(continue_engine.router)
app.include_router(billing.router)
app.include_router(billing.payments_router)
app.include_router(home.router)
app.include_router(knows_you.router)
app.include_router(project_intelligence_phase2.router)
app.include_router(timeline_phase3.router)
app.include_router(learning_engine_phase4.router)
app.include_router(learning_evaluation.router)
app.include_router(relationship_graph_phase5.router)
app.include_router(context_engine_phase6.router)
app.include_router(daily_engine.router)
app.include_router(continuity_assistant_phase7.router)
app.include_router(daily_brief_phase8.router)
app.include_router(decision_graph.router, dependencies=[Depends(get_current_user)])
app.include_router(decision_intelligence.router, dependencies=[Depends(get_current_user)])
app.include_router(decision_simulator.router, dependencies=[Depends(get_current_user)])
app.include_router(open_loops_engine.router)
app.include_router(notifications.router)
app.include_router(product_analytics.router)
app.include_router(evolution_engine.router, dependencies=[Depends(get_current_user)])
app.include_router(intelligence_dataset.router, dependencies=[Depends(get_current_user)])
app.include_router(intelligence_loop.router, dependencies=[Depends(get_current_user)])
app.include_router(life_graph.router, dependencies=[Depends(get_current_user)])
app.include_router(memory_feed.router, dependencies=[Depends(get_current_user)])
app.include_router(opportunity.router, dependencies=[Depends(get_current_user)])
app.include_router(action_center.router, dependencies=[Depends(get_current_user)])
app.include_router(pkm.router, dependencies=[Depends(get_current_user)])
app.include_router(privacy_intelligence.router, dependencies=[Depends(get_current_user)])
app.include_router(reasoning_engine.router)
app.include_router(skills.router, dependencies=[Depends(get_current_user)])
app.include_router(skill_marketplace.router, dependencies=[Depends(get_current_user)])
app.include_router(synzept_protocol.router, dependencies=[Depends(get_current_user)])
app.include_router(time_machine.router, dependencies=[Depends(get_current_user)])
app.include_router(trust_engine.router, dependencies=[Depends(get_current_user)])
app.include_router(workspace_os.router, dependencies=[Depends(get_current_user)])
app.include_router(agent_runtime.router, dependencies=[Depends(get_current_user)])
app.include_router(coach.router, dependencies=[Depends(get_current_user)])
app.include_router(onboarding_wow.router, dependencies=[Depends(get_current_user)])
app.include_router(executions.router)
app.include_router(execute.router)


@app.get("/api/system/auth-health", dependencies=[Depends(get_current_user)])
async def auth_health():
    return build_auth_health_report()


@app.get("/health")
async def health():
    db = await database_diagnostics()
    db_ok = bool(db["connected"])
    return {
        "status": "ok" if db_ok else "degraded",
        "service": "synzept-backend",
        "database": "connected" if db_ok else "unavailable",
        "migration_version": db.get("migration_version"),
        "background_worker": "redis" if settings.use_background_worker else "asyncio",
    }

@app.get("/health/diagnostics", dependencies=[Depends(get_current_user)])
async def diagnostics():
    db = await database_diagnostics()
    return {
        "database": db,
        "ai": ProviderRegistry().availability(),
        "retrieval": await retrieval_diagnostics(),
        "metrics": monitor.snapshot(),
        "background_worker": "redis" if settings.use_background_worker else "asyncio",
    }


@app.get("/health/ready")
async def readiness():
    if not await check_database():
        return JSONResponse(status_code=503, content={"ready": False, "database": "unavailable"})
    ai = ProviderRegistry().availability()
    return {"ready": True, "ai_available": ai["available"], "migration_version": (await database_diagnostics()).get("migration_version")}

@app.get("/health/ai")
async def ai_health():
    status = ProviderRegistry().availability()
    code = 200 if status["available"] else 503
    return JSONResponse(status_code=code, content=status)

@app.get("/health/retrieval")
async def retrieval_health():
    status = await retrieval_diagnostics()
    return JSONResponse(status_code=200, content=status)

@app.get("/health/metrics", dependencies=[Depends(get_current_user)])
async def metrics_health():
    return monitor.snapshot()


app = OuterCORSMiddleware(
    app,
    allow_origins=settings.cors_origin_list,
    allow_credentials=True,
    allow_methods=CORS_METHODS,
    allow_headers=CORS_HEADERS,
)
