import type { DecisionIntelligenceData } from "./types";

export const decisionIntelligenceMock: DecisionIntelligenceData = {
  generatedAt: "2026-07-07T17:10:00+05:30",
  detectionCandidates: [
    {
      id: "detect-memory-feed-home",
      sourceType: "conversation",
      sourceTitle: "Memory Feed planning",
      suggestedTitle: "Make Memory Feed the first authenticated screen",
      rationale: "The language contains a clear product direction, implementation commitment, and user-facing consequence.",
      confidence: 0.91,
      shouldSuggestDecision: true,
      evidence: [{ id: "ev-detect-1", sourceType: "conversation", sourceTitle: "Memory Feed planning", quote: "Memory Feed is the first screen users see after opening Synzept.", strength: 94 }],
    },
    {
      id: "detect-command-bar-placement",
      sourceType: "note",
      sourceTitle: "Workspace OS architecture note",
      suggestedTitle: "Place the command bar in the global shell",
      rationale: "This is a cross-product architectural choice with persistent UX impact.",
      confidence: 0.86,
      shouldSuggestDecision: true,
      evidence: [{ id: "ev-detect-2", sourceType: "note", sourceTitle: "Workspace OS architecture note", quote: "Commands must be accessible from anywhere in the workspace.", strength: 88 }],
    },
  ],
  decisions: [
    {
      id: "decision-memory-feed-home",
      title: "Make Memory Feed the default home surface",
      description: "The first screen should proactively answer what changed, what matters, what needs attention, and what commitments may be forgotten.",
      importance: "High",
      mission: "Synzept V2 Memory Feed",
      goal: "Increase return-user clarity and retention.",
      relatedProjects: ["Memory Feed", "Workspace OS"],
      relatedPeople: ["Beta reviewers"],
      alternativesConsidered: ["Keep static dashboard", "Open directly into chat", "Show only Daily Brief"],
      expectedOutcome: "Users understand their day and unfinished work within the first minute.",
      risks: ["Could overload users if too many cards appear", "Ranking may feel opaque without explanations"],
      confidence: 0.84,
      currentStatus: "Accepted",
      reviewState: "Pending",
      decidedAt: "2026-07-07T08:45:00+05:30",
      reviewDueAt: "2026-07-14T09:00:00+05:30",
      evidence: [{ id: "ev-decision-1", sourceType: "conversation", sourceTitle: "Memory Feed requirements", quote: "Show only 5-7 cards to avoid overload.", strength: 90 }],
    },
    {
      id: "decision-mock-first",
      title: "Build V2 intelligence systems with realistic mock data first",
      description: "New intelligence surfaces should prove contracts, ranking, and UX before touching production user data.",
      importance: "High",
      mission: "Synzept V2 Architecture",
      goal: "Reduce product and privacy risk while moving quickly.",
      relatedProjects: ["Decision Intelligence", "Intelligence Loop", "Trust Engine"],
      relatedPeople: [],
      alternativesConsidered: ["Connect production retrieval immediately", "Hard-code UI only", "Delay backend APIs"],
      expectedOutcome: "The platform can be tested end-to-end without production data dependencies.",
      risks: ["Mock behavior may hide integration complexity", "Teams may overfit to ideal data"],
      confidence: 0.89,
      currentStatus: "Accepted",
      reviewState: "Completed",
      decidedAt: "2026-07-06T18:10:00+05:30",
      reviewDueAt: "2026-07-07T18:00:00+05:30",
      evidence: [{ id: "ev-decision-2", sourceType: "decision", sourceTitle: "Production data boundary", quote: "Do not connect to production data yet.", strength: 96 }],
    },
    {
      id: "decision-approval-layer",
      title: "Require explicit approval before meaningful agent actions",
      description: "Agents may prepare drafts, plans, and recommendations, but should request permission before changing state or contacting people.",
      importance: "Critical",
      mission: "Agent Trust",
      goal: "Make users comfortable delegating work to Synzept agents.",
      relatedProjects: ["Agent Workspace", "Trust Engine"],
      relatedPeople: ["Beta reviewers"],
      alternativesConsidered: ["Auto-execute low-risk actions", "Disable actions entirely", "Ask approval only for external messages"],
      expectedOutcome: "Users trust agents because control remains visible and reversible.",
      risks: ["Too many approvals may slow workflow", "Approval copy must be clear"],
      confidence: 0.82,
      currentStatus: "Accepted",
      reviewState: "Outcome Unknown",
      decidedAt: "2026-07-07T10:20:00+05:30",
      reviewDueAt: "2026-07-21T09:00:00+05:30",
      evidence: [{ id: "ev-decision-3", sourceType: "architecture", sourceTitle: "Intelligence Loop", quote: "Before executing any meaningful action, request explicit user approval.", strength: 92 }],
    },
  ],
  reviews: [
    { id: "review-memory-feed-home", decisionId: "decision-memory-feed-home", decisionTitle: "Make Memory Feed the default home surface", reviewState: "Pending", scheduledFor: "2026-07-14T09:00:00+05:30", prompt: "Did the first screen improve clarity or create overload?", recommendedUpdate: "Compare beta feedback against expected first-minute clarity." },
    { id: "review-mock-first", decisionId: "decision-mock-first", decisionTitle: "Build V2 intelligence systems with realistic mock data first", reviewState: "Completed", scheduledFor: "2026-07-07T18:00:00+05:30", prompt: "Did mock-first development reduce integration risk?", recommendedUpdate: "Keep the mock API boundary and add contract tests before production wiring." },
  ],
  outcomeAnalyses: [
    {
      id: "outcome-mock-first",
      decisionId: "decision-mock-first",
      expectedOutcome: "The platform can be tested end-to-end without production data dependencies.",
      actualOutcome: "Multiple V2 engines now have service, API, UI, docs, and tests without production connections.",
      predictionAccuracy: 87,
      lessonsLearned: ["Mock-first is effective when schemas are production-shaped.", "Contract tests matter more than visual-only prototypes."],
      futureEvidence: ["Prefer mock API + service + tests for new intelligence engines."],
      confidence: 0.83,
    },
  ],
  decisionDNA: [
    { id: "dna-strength-contracts", category: "Common Strength", title: "Strong architectural boundary setting", summary: "High-performing decisions explicitly define production-data boundaries, approval boundaries, and service contracts.", confidence: 0.86, supportingEvidence: ["decision-mock-first", "decision-approval-layer"] },
    { id: "dna-pattern-mock-first", category: "High-Performing Pattern", title: "Mock-first implementation before production wiring", summary: "Decisions perform well when the system proves UX and API contracts before data integration.", confidence: 0.82, supportingEvidence: ["outcome-mock-first"] },
    { id: "dna-blindspot-overbuilding", category: "Blind Spot", title: "Risk of adding surfaces before integration", summary: "The user tends to create powerful modules quickly; the recurring risk is fragmentation before a unifying layer is stable.", confidence: 0.74, supportingEvidence: ["decision-memory-feed-home", "decision-approval-layer"] },
    { id: "dna-mistake-review-delay", category: "Recurring Mistake", title: "Outcome reviews can be delayed", summary: "Decisions are captured faster than they are reviewed, reducing learning quality unless review prompts are surfaced.", confidence: 0.69, supportingEvidence: ["review-memory-feed-home"] },
  ],
  recommendations: [
    { id: "rec-keep-mock-contract", title: "Use mock-first contracts for Decision Intelligence production rollout", scenario: "When deciding how to connect this engine to real conversations and notes.", recommendation: "Keep detection and outcome analysis behind mock contracts until review workflows pass tests.", reasoning: "The mock-first decision already produced a high-accuracy outcome and lowers privacy risk.", relevantDecisionIds: ["decision-mock-first"], confidence: 0.87, expectedImpact: 91 },
    { id: "rec-use-past-approval", title: "Use the approval-layer decision for future agent automation choices", scenario: "When deciding whether an agent should execute an action automatically.", recommendation: "Default to explicit approval until repeated successful outcomes justify lower friction.", reasoning: "The approval-layer decision has high importance, trust implications, and clear evidence from the Intelligence Loop.", relevantDecisionIds: ["decision-approval-layer"], confidence: 0.84, expectedImpact: 88 },
  ],
  analytics: {
    totalDecisions: 3,
    pendingReviews: 1,
    completedReviews: 1,
    averagePredictionAccuracy: 87,
    highConfidenceSuccessRate: 82,
    recurringRiskThemes: ["Overload", "Fragmentation", "Approval fatigue", "Delayed reviews"],
  },
};
